<?php

namespace Database\Seeders;

use App\Models\Barangay;
use App\Models\Municipality;
use Illuminate\Database\Seeder;

class BarangaySeeder extends Seeder
{
    public function run(): void
    {
        $barangays = [
            // BIÑAN CITY
            ['code' => 'LAG-BC-B1', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B2', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B3', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B4', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B5', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B6', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B7', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-B8', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-BA', 'name' => 'Balanac', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-BA', 'name' => 'Binan', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-CA', 'name' => 'Casile', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-DA', 'name' => 'Dela Costa', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-GA', 'name' => 'Ganado', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-MA', 'name' => 'Malaban', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-MU', 'name' => 'Mampalasan', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-PL', 'name' => 'Plaridel', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-SA', 'name' => 'San Antonio', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-SJ', 'name' => 'San Jose', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-SM', 'name' => 'San Miguel', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-SP', 'name' => 'San Pascual', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-SR', 'name' => 'San Roque', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-SC-SV', 'name' => 'Santo Nino (Pob.)', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-TA', 'name' => 'Tubigan', 'municipality_code' => 'LAG-BC'],
            ['code' => 'LAG-BC-ZA', 'name' => 'Zapote', 'municipality_code' => 'LAG-BC'],
            
            // CALAMBA CITY
            ['code' => 'LAG-CA-B1', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-B2', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-B3', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-B4', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-B5', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-BA', 'name' => 'Bucal', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-BA', 'name' => 'Bunggo', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-CM', 'name' => 'Canlubang', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-CM', 'name' => 'Canlubang (North)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-CM', 'name' => 'Canlubang (South)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-LE', 'name' => 'Lecheria', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-MA', 'name' => 'Makiling', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-MR', 'name' => 'Majada', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-MR', 'name' => 'Majada (North)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-MR', 'name' => 'Majada (South)', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-MA', 'name' => 'Mapagkawalaan', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-PA', 'name' => 'Palingon', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-PR', 'name' => 'Poblacion', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-SA', 'name' => 'San Cristobal', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-SI', 'name' => 'Santo Tomas', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-SU', 'name' => 'Sinalhan', 'municipality_code' => 'LAG-CA'],
            ['code' => 'LAG-CA-TU', 'name' => 'Turbina', 'municipality_code' => 'LAG-CA'],
            
            // CAVINTI
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-CA', 'name' => 'Calumpang', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-CA', 'name' => 'Cansuso', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-DA', 'name' => 'Duhat', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-HI', 'name' => 'Hibilo', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-MA', 'name' => 'Makiling', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-PA', 'name' => 'Poblacion', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-PU', 'name' => 'Puto', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-SA', 'name' => 'Santo Tomas', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-TA', 'name' => 'Tatlong Kahoy', 'municipality_code' => 'LAG-CV'],
            ['code' => 'LAG-CV-TI', 'name' => 'Tibag', 'municipality_code' => 'LAG-CV'],
            
            // FAMY
            ['code' => 'LAG-FG-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-MA', 'name' => 'Mahipon', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-NA', 'name' => 'Narra', 'municipality_code' => 'LAG-FG'],
            ['code' => 'LAG-FG-SI', 'name' => 'Santo Rosario', 'municipality_code' => 'LAG-FG'],
            
            // KALAYAAN
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-SI', 'name' => 'San Antonio', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-SI', 'name' => 'San Juan', 'municipality_code' => 'LAG-KL'],
            ['code' => 'LAG-KL-SI', 'name' => 'San Miguel', 'municipality_code' => 'LAG-KL'],
            
            // LOS BAÑOS
            ['code' => 'LAG-LB-AN', 'name' => 'Anos', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Babayasan', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Bagong Silang', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Bambang', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Batong Malake', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Bayan Bayanan', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Bayog', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Buhanginan', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-BA', 'name' => 'Lalakay', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-MA', 'name' => 'Malamig', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-MA', 'name' => 'Maahas', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-PA', 'name' => 'Poblacion', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-SA', 'name' => 'Santo Tomas', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-TI', 'name' => 'Tadlac', 'municipality_code' => 'LAG-LB'],
            ['code' => 'LAG-LB-UG', 'name' => 'Uwisan', 'municipality_code' => 'LAG-LB'],
            
            // LUMBAN
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            ['code' => 'LAG-LU-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-LU'],
            
            // MABITAC
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-AM', 'name' => 'Amuyong', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-DA', 'name' => 'Dasay', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-LU', 'name' => 'Luisiana', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-MA', 'name' => 'Matalavita', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-NA', 'name' => 'Narra', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-PA', 'name' => 'Pangil', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-RO', 'name' => 'Rizal', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-SA', 'name' => 'San Antonio', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-SJ', 'name' => 'San Jose', 'municipality_code' => 'LAG-MG'],
            ['code' => 'LAG-MG-SM', 'name' => 'San Miguel', 'municipality_code' => 'LAG-MG'],
            
            // MAJAYJAY
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            ['code' => 'LAG-MJ-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-MJ'],
            
            // NAGCARLAN
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            ['code' => 'LAG-ND-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-ND'],
            
            // PAGSANJAN
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            ['code' => 'LAG-PA-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-PA'],
            
            // PAKIL
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            ['code' => 'LAG-PK-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-PK'],
            
            // PANGIL
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            ['code' => 'LAG-PG-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-PG'],
            
            // PEDRO CABUNGAO
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            ['code' => 'LAG-PC-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-PC'],
            
            // RIZAL
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            ['code' => 'LAG-RI-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-RI'],
            
            // SAN PABLO CITY
            ['code' => 'LAG-SB-AN', 'name' => 'San Anton (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santo Angel', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santo Cristo', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Jose', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Mateo', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Miguel', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Nicolas', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Pedro', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Roque', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'San Vicente', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santiago', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santo Nino', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santa Cruz', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santa Maria', 'municipality_code' => 'LAG-SB'],
            ['code' => 'LAG-SB-AN', 'name' => 'Santo Tomas', 'municipality_code' => 'LAG-SB'],
            
            // SANTA CRUZ
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 21 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 22 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 23 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 24 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 25 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            ['code' => 'LAG-SC-BA', 'name' => 'Barangay 26 (Poblacion)', 'municipality_code' => 'LAG-SC'],
            
            // SANTA MARIA
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 21 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            ['code' => 'LAG-SM-BA', 'name' => 'Barangay 22 (Poblacion)', 'municipality_code' => 'LAG-SM'],
            
            // SINILOAN
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 21 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 22 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            ['code' => 'LAG-SI-BA', 'name' => 'Barangay 23 (Poblacion)', 'municipality_code' => 'LAG-SI'],
            
            // VICTORIA
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 1 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 2 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 3 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 4 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 5 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 6 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 7 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 8 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 9 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 10 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 11 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 12 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 13 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 14 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 15 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 16 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 17 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 18 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 19 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 20 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 21 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 22 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 23 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 24 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 25 (Poblacion)', 'municipality_code' => 'LAG-VI'],
            ['code' => 'LAG-VI-BA', 'name' => 'Barangay 26 (Poblacion)', 'municipality_code' => 'LAG-VI'],
        ];

        foreach ($barangays as $barangay) {
            $municipality = Municipality::where('code', $barangay['municipality_code'])->first();
            
            if ($municipality) {
                Barangay::updateOrCreate(
                    ['code' => $barangay['code']],
                    [
                        'name' => $barangay['name'],
                        'municipality_id' => $municipality->id,
                    ]
                );
            }
        }
    }
}
