@extends('layouts.app')

@section('page_title', 'Dashboard')

@section('content')
<div class="alert alert-primary border-0 d-flex justify-content-between align-items-center mb-4"><div><strong>Welcome to PWD Registry.</strong> Monitor applications and manage PWD records from one place.</div><a href="{{ route('registrants.create') }}" class="btn btn-primary btn-sm bg-white text-primary border-0">+ New Registration</a></div>
<div class="row g-4 mb-4">
    <div class="col-lg-3 col-6"><div class="small-box text-bg-primary"><div class="inner"><h3>{{ number_format($totalRegistrants) }}</h3><p>Total PWD Registrants</p></div><div class="icon"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 8v8"/><path d="M8 12h8"/></svg></div><a href="{{ route('registrants.index') }}" class="small-box-footer link-light">View registry <span>→</span></a></div></div>
    <div class="col-lg-3 col-6"><div class="small-box text-bg-success"><div class="inner"><h3>{{ number_format($activeCards) }}</h3><p>Active PWD Cards</p></div><div class="icon"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg></div><a href="{{ route('registrants.index') }}" class="small-box-footer link-light">View registry <span>→</span></a></div></div>
    <div class="col-lg-3 col-6"><div class="small-box text-bg-warning"><div class="inner"><h3>{{ number_format($pendingApplications) }}</h3><p>Pending Applications</p></div><div class="icon"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg></div><a href="{{ route('applications.index') }}" class="small-box-footer link-dark">Review applications <span>→</span></a></div></div>
    <div class="col-lg-3 col-6"><div class="small-box text-bg-danger"><div class="inner"><h3>{{ number_format($expiringCards) }}</h3><p>Cards Expiring Soon</p></div><div class="icon"><svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg></div><a href="{{ route('registrants.index') }}" class="small-box-footer link-light">View registry <span>→</span></a></div></div>
</div>
<div class="row g-4">
<div class="col-lg-8"><div class="card"><div class="card-header d-flex justify-content-between align-items-center"><h3 class="card-title">Recent Applications</h3><a href="{{ route('applications.index') }}" class="btn btn-sm btn-outline-primary">View All</a></div><div class="card-body p-0"><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Application No.</th><th>Registrant</th><th>Type</th><th>Submitted</th><th>Status</th></tr></thead><tbody>@forelse($recentApplications as $application)<tr><td class="fw-semibold">{{ $application->application_number }}</td><td>{{ $application->registrant->first_name }} {{ $application->registrant->last_name }}</td><td class="text-capitalize">{{ $application->type }}</td><td>{{ optional($application->submitted_at)->format('M d, Y') ?? '—' }}</td><td><span class="badge text-bg-{{ $application->status === 'approved' ? 'success' : ($application->status === 'pending' ? 'warning' : 'secondary') }} text-capitalize">{{ str_replace('_', ' ', $application->status) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No applications have been recorded yet.</td></tr>@endforelse</tbody></table></div></div>@if($recentApplications->hasPages())<div class="card-footer">{{ $recentApplications->onEachSide(1)->links() }}</div>@endif</div></div>
    <div class="col-lg-4"><div class="card mb-4"><div class="card-header"><h3 class="card-title">Quick Actions</h3></div><div class="card-body d-grid gap-2"><a href="{{ route('registrants.create') }}" class="btn btn-primary d-flex align-items-center justify-content-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg> Register New PWD</a><a href="{{ route('applications.index') }}" class="btn btn-outline-primary d-flex align-items-center justify-content-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg> Review Pending Applications</a><a href="{{ route('registrants.index') }}" class="btn btn-outline-secondary d-flex align-items-center justify-content-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg> Browse Registry</a></div></div><div class="card"><div class="card-header"><h3 class="card-title">Registry Overview</h3></div><div class="card-body"><div class="d-flex justify-content-between align-items-center border-bottom pb-3 mb-3"><span class="text-muted">Cards needing attention</span><strong class="fs-5">{{ number_format($expiringCards) }}</strong></div><div class="d-flex justify-content-between align-items-center"><span class="text-muted">Application queue</span><strong class="fs-5">{{ number_format($pendingApplications) }}</strong></div></div></div></div>
</div>
@endsection
