@extends('layouts.app')
@section('page_title', 'Registrant Profile')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-4 mb-4"><div class="col-lg-4"><div class="card"><div class="card-body text-center"><div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 rounded-circle mb-3" style="width: 80px; height: 80px;"><svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="text-primary"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div><h3 class="h4 fw-bold mb-1">{{ $registrant->first_name }} {{ $registrant->last_name }}</h3><p class="text-muted mb-2">{{ $registrant->pwd_id_number }}</p><span class="badge text-bg-{{ $registrant->card_status === 'active' ? 'success' : 'secondary' }} text-capitalize">{{ $registrant->card_status }}</span></div></div></div>
<div class="col-lg-8"><div class="card"><div class="card-header"><h3 class="card-title">Personal Information</h3></div><div class="card-body"><div class="row"><div class="col-md-6"><dl class="row"><dt class="col-sm-5 text-muted">PWD ID Number</dt><dd class="col-sm-7 fw-semibold">{{ $registrant->pwd_id_number }}</dd><dt class="col-sm-5 text-muted">Birth Date</dt><dd class="col-sm-7">{{ $registrant->birth_date->format('M d, Y') }}</dd><dt class="col-sm-5 text-muted">Sex</dt><dd class="col-sm-7 text-capitalize">{{ $registrant->sex }}</dd><dt class="col-sm-5 text-muted">Civil Status</dt><dd class="col-sm-7">{{ $registrant->civil_status ?: '—' }}</dd></dl></div><div class="col-md-6"><dl class="row"><dt class="col-sm-5 text-muted">Disability Type</dt><dd class="col-sm-7 fw-semibold">{{ $registrant->disabilityType->name }}</dd><dt class="col-sm-5 text-muted">Barangay</dt><dd class="col-sm-7">{{ $registrant->barangay->name }}</dd><dt class="col-sm-5 text-muted">Contact Number</dt><dd class="col-sm-7">{{ $registrant->contact_number ?: '—' }}</dd><dt class="col-sm-5 text-muted">Email</dt><dd class="col-sm-7">{{ $registrant->email ?: '—' }}</dd></dl></div></div></div></div></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Address Information</h3></div><div class="card-body"><dl class="mb-0"><dt class="text-muted">Home Address</dt><dd class="fw-semibold">{{ $registrant->address_line }}</dd></dl></div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header"><h3 class="card-title">Card Information</h3></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-5 text-muted">Card Issued</dt><dd class="col-sm-7">{{ optional($registrant->card_issued_date)->format('M d, Y') ?? '—' }}</dd><dt class="col-sm-5 text-muted">Card Expiry</dt><dd class="col-sm-7">{{ optional($registrant->card_expiry_date)->format('M d, Y') ?? '—' }}</dd></dl></div></div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Emergency Contact</h3></div><div class="card-body"><div class="row"><div class="col-md-6"><dl class="row"><dt class="col-sm-5 text-muted">Guardian Name</dt><dd class="col-sm-7">{{ $registrant->guardian_name ?: '—' }}</dd></dl></div><div class="col-md-6"><dl class="row"><dt class="col-sm-5 text-muted">Emergency Contact</dt><dd class="col-sm-7">{{ $registrant->emergency_contact_name ?: '—' }}</dd><dt class="col-sm-5 text-muted">Emergency Number</dt><dd class="col-sm-7">{{ $registrant->emergency_contact_number ?: '—' }}</dd></dl></div></div></div><div class="card-footer"><a href="{{ route('registrants.index') }}" class="btn btn-outline-secondary d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 12H5M12 19l-7-7 7-7"/></svg> Back to Registry</a></div></div>
@endsection
