@extends('layouts.app')
@section('page_title', 'Review Application')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-2"><a href="{{ route('applications.index') }}" class="btn btn-outline-secondary d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 12H5M12 19l-7-7 7-7"/></svg> Back to Applications</a><div class="d-flex gap-2 flex-wrap"><a href="{{ route('applications.edit', $application) }}" class="btn btn-outline-primary d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg> Edit Review</a><form method="POST" action="{{ route('applications.status', $application) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="pending"><button class="btn btn-primary d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 13l4 4L19 7"/></svg> Submit</button></form><form method="POST" action="{{ route('applications.status', $application) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="under_review"><button class="btn btn-warning d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg> Under Review</button></form><form method="POST" action="{{ route('applications.status', $application) }}" onsubmit="return confirm('Decline this application?')">@csrf @method('PATCH')<input type="hidden" name="status" value="rejected"><button class="btn btn-outline-danger d-flex align-items-center gap-2"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg> Decline</button></form></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="card mb-4"><div class="card-header d-flex justify-content-between align-items-center"><h3 class="card-title">{{ $application->application_number }}</h3><span class="badge text-bg-{{ $application->status === 'approved' ? 'success' : ($application->status === 'pending' ? 'warning' : 'secondary') }} text-capitalize">{{ str_replace('_', ' ', $application->status) }}</span></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4 text-muted">Application Type</dt><dd class="col-sm-8 text-capitalize fw-semibold">{{ $application->type }}</dd><dt class="col-sm-4 text-muted">Submitted</dt><dd class="col-sm-8">{{ optional($application->submitted_at)->format('M d, Y h:i A') ?? 'Not submitted' }}</dd><dt class="col-sm-4 text-muted">Reviewed by</dt><dd class="col-sm-8">{{ $application->reviewer?->name ?? 'Not yet reviewed' }}</dd><dt class="col-sm-4 text-muted">Approved</dt><dd class="col-sm-8">{{ optional($application->approved_at)->format('M d, Y h:i A') ?? 'Not yet approved' }}</dd><dt class="col-sm-4 text-muted">Review Notes</dt><dd class="col-sm-8">{{ $application->notes ?: 'No notes recorded.' }}</dd></dl></div></div><div class="card border-danger bg-danger bg-opacity-5">
    <div class="card-body d-flex justify-content-between align-items-center">
        <div>
            <h5 class="text-white mb-1">Archive application</h5>
            <p class="small text-white-50 mb-0">The application will be soft deleted and can be recovered from the database.</p>
        </div>
        <form method="POST" action="{{ route('applications.destroy', $application) }}" onsubmit="return confirm('Archive this application?')">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger d-flex align-items-center gap-2">
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                    <polyline points="3 6 5 6 21 6"/>
                    <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>
                </svg>
                Archive
            </button>
        </form>
    </div>
</div></div>
<div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">Registrant Details</h3></div><div class="card-body"><div class="text-center mb-3"><div class="d-inline-flex align-items-center justify-content-center bg-primary bg-opacity-10 rounded-circle mb-2" style="width: 64px; height: 64px;"><svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" class="text-primary"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div><p class="fw-semibold mb-1">{{ $application->registrant->first_name }} {{ $application->registrant->last_name }}</p><p class="small text-muted">{{ $application->registrant->pwd_id_number }}</p></div><hr><dl class="mb-0"><dt class="small text-muted">Disability Type</dt><dd class="fw-semibold">{{ $application->registrant->disabilityType->name }}</dd><dt class="small text-muted">Barangay</dt><dd>{{ $application->registrant->barangay->name }}</dd><dt class="small text-muted">Contact</dt><dd>{{ $application->registrant->contact_number ?: '—' }}</dd></dl><a class="btn btn-sm btn-outline-primary w-100 mt-3 d-flex align-items-center justify-content-center gap-2" href="{{ route('registrants.show', $application->registrant) }}"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg> View Profile</a></div></div></div></div>
@endsection
